# baseurl - url prefix for the site e.g. http://my.site/myprefix/
baseurl: 
baseTitle: M Y K Y T A&nbsp;&nbsp;&nbsp;L Y S K O V
excerpt_separator: <!--more-->
title: Mykyta Lyskov's Home Site
description: Mykyta Lyskov's Home Site
author: Mykyta Lyskov
logo: /pictures/logos/Head-blink.gif
email: nikitaliskov@gmail.com
url: http://nikitaliskov.com
sidebar:
  - 
    category: animation 
  - 
    category: pictures
    class: calendar
  - 
    category: contacts
exclude:
  - old
  - bak
# not used
lang:
  - en
  - ru
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
permalink: /:categories/:title
# not used
collections:
  animation:
    output: true
    permalink: /:collection/:name
  pictures:
    output: true
    permalink: /:collection/:name
# show future posts
future: true
