# baseurl - url prefix for the site e.g. http://my.site/myprefix/
baseurl: 
baseTitle: Mykyta Lyskov
excerpt_separator: <!--more-->
title: Mykyta Lyskov's Home Site
description: Mykyta Lyskov's Home Site
url: https://nikitaliskov.github.io
author: Mykyta Lyskov
logo: /pictures/logos/Head-blink.gif
email: nikitaliskov@gmail.com
exclude:
  - old
  - bak
lang:
  - en
  - ru
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
permalink: /:categories/:title
collections:
  animation:
    output: true
    permalink: /:collection/:name
  pictures:
    output: true
    permalink: /:collection/:name
# show future posts
future: true
