# baseurl - url prefix for the site e.g. http://my.site/myprefix/
baseurl: 
baseTitle: N I K I T A&nbsp;&nbsp;&nbsp;L I S K O V
excerpt_separator: <!--more-->
title: Nikita Liskov's Home Site
description: Nikita Liskov's Home Site
author: Nikita Liskov
author_short: mykyta-lyskov
logo: /pictures/logos/Head-blink.gif
email: nikitaliskov@gmail.com
url: http://nikitaliskov.com
sidebar:
  -
    category: narrative-films
  -
    category: music-video
  -
    category: abstract-films
  -
    category: student-films
  # - 
  #   category: pictures
  #   class: calendar
  -
    category: press
  -
    category: contacts
  -
    category: cv
exclude:
  - old
  - bak

# not used
lang:
  - en
  - ru

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
permalink: /:categories/:title

# not working
# configuring collection_dir is not available in 3.6.0. Its slated for v3.7.0
# collections_dir: site2
# collections:
#   animation:
#     output: true
#     permalink: /:collection/:name
#   pictures:
#     output: true
#     permalink: /:collection/:name

# show future posts
future: true

# not used
media_root: site
